name: "selenium_electricity"
version: "v1.5.2"
slug: selenium_electricity
description: "Make sgcc electricity data available in HA"
arch:
  - amd64
  - aarch64
homeassistant_api: true
options:
  phoneNumber: null
  password: null
  logLevel: "INFO"
schema:
  phoneNumber: str
  password: str
  logLevel: list(DEBUG|INFO|WARNING|ERROR|FATAL)?
image: dscao/addon-sgcc-electricity-{arch}
